if(EXISTS "/home/pabut/IVS_Project1/libs/black_box_test[1]_tests.cmake")
  include("/home/pabut/IVS_Project1/libs/black_box_test[1]_tests.cmake")
else()
  add_test(black_box_test_NOT_BUILT black_box_test_NOT_BUILT)
endif()
